import*as THREE from'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{scaledAnthropometry}from'./anthropometry-v01.js';
const A=scaledAnthropometry(1.75),H=A.stature,app=document.getElementById('app'),M=document.getElementById('metrics'),LR=document.getElementById('labels');
const S=new THREE.Scene();S.background=new THREE.Color(0x0b0d12);const C=new THREE.PerspectiveCamera(32,innerWidth/innerHeight,.01,100),R=new THREE.WebGLRenderer({antialias:true});R.setSize(innerWidth,innerHeight);R.setPixelRatio(Math.min(devicePixelRatio,2));app.appendChild(R.domElement);const O=new OrbitControls(C,R.domElement);O.enableDamping=true;O.enablePan=false;O.target.set(0,.9,0);S.add(new THREE.HemisphereLight(0xdde8ff,0x1d2330,2.2));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(4,6,5);S.add(dl);const G=new THREE.GridHelper(4,40,0x32405a,0x202735);G.position.y=.002;S.add(G);
const MB=new THREE.MeshStandardMaterial({color:0xd7dbe7}),MJ=new THREE.MeshStandardMaterial({color:0xf0a65b}),MF=new THREE.MeshStandardMaterial({color:0x8a95ae}),MS=new THREE.MeshStandardMaterial({color:0xb8a8ff}),ME=new THREE.MeshStandardMaterial({color:0x7cc7ff});const root=new THREE.Group();S.add(root);const N={},B=[];
function n(k,x,y,z,r=.018,m=MJ){const q=new THREE.Mesh(new THREE.SphereGeometry(r,14,10),m);q.position.set(x,y,z);root.add(q);N[k]=q}function b(a,c,r=.011,m=MB){const q=new THREE.Mesh(new THREE.CylinderGeometry(r,r,1,10),m);root.add(q);B.push([q,a,c])}function sync(){for(const[q,a,c]of B){const p=N[a].position,d=N[c].position,v=d.clone().sub(p);q.position.copy(p).add(d).multiplyScalar(.5);q.scale.set(1,v.length(),1);q.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize())}}
const gl=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,H+.05,0)]),new THREE.LineBasicMaterial({color:0xff7f7f}));S.add(gl);
const ankle=A.ankleJointHeight,knee=ankle+A.tibia,hip=knee+A.femur,hz=.014,kz=-.024,az=-.048,hx=A.hipCenterHalfWidth,sx=A.shoulderJointHalfWidth;
const s1=hip+.125,l1=s1+.18,t12=l1+.022,t1=t12+.30,c7=t1+.022,c1=c7+.105,sk=H-A.headHeight*.5;const L=[];function V(k,y,z,r){n(k,0,y,z,r,MS);L.push(k)}function sm(a,z,t){t=t*t*(3-2*t);return a+(z-a)*t}
V('S1',s1,-.010,.022);['L5','L4','L3','L2','L1'].forEach((k,i)=>{let t=(i+1)/5,z=i<2?sm(-.010,.006,(i+1)/2):sm(.006,-.005,(i-1)/3);V(k,s1+(l1-s1)*t,z,.019)});Array.from({length:12},(_,i)=>'T'+(12-i)).forEach((k,i)=>{let t=(i+1)/12,z=t<=.5?sm(-.005,-.050,t/.5):sm(-.050,-.020,(t-.5)/.5);V(k,t12+(t1-t12)*t,z,.016)});['C7','C6','C5','C4','C3','C2','C1'].forEach((k,i)=>{let t=(i+1)/7;V(k,c7+(c1-c7)*t,sm(-.020,-.004,t),.013)});for(let i=0;i<L.length-1;i++)b(L[i],L[i+1],.009,MS);n('skull',0,sk,0,A.headHeight*.42,MS);n('crown',0,H,0,.012,ME);b('C1','skull',.009,MS);b('skull','crown',.007,MS);
const px=A.pelvisWidth*.5,pz=A.pelvisDepth*.5;n('hipL',-hx,hip,hz,.029);n('hipR',hx,hip,hz,.029);[['pTL',-px,s1+.055,-.035],['pTR',px,s1+.055,-.035],['pFL',-px*.75,s1-.01,pz*.7],['pFR',px*.75,s1-.01,pz*.7],['pBL',-px*.7,s1-.005,-pz*.75],['pBR',px*.7,s1-.005,-pz*.75]].forEach(v=>n(v[0],v[1],v[2],v[3],.013,MF));[['pTL','pFL'],['pFL','hipL'],['pBL','pTL'],['pBL','S1'],['pTR','pFR'],['pFR','hipR'],['pBR','pTR'],['pBR','S1'],['pTL','pTR']].forEach(v=>b(v[0],v[1],.009,MF));
function ring(v,w,f,d){let p=N[v].position;n(v+'L',-w,p.y,p.z,.01,MF);n(v+'R',w,p.y,p.z,.01,MF);n(v+'F',0,p.y,p.z+f,.01,MF);n(v+'B',0,p.y,p.z-d,.01,MF);[['L','F'],['R','F'],['L','B'],['R','B']].forEach(x=>b(v+x[0],v+x[1],.007,MF));b(v,v+'B',.007,MF)}ring('T3',A.upperThoraxWidth*.48,A.ribCageDepth*.30,A.ribCageDepth*.25);ring('T7',A.ribCageWidth*.50,A.ribCageDepth*.50,A.ribCageDepth*.38);ring('T11',A.ribCageWidth*.43,A.ribCageDepth*.38,A.ribCageDepth*.30);
const sy=N.T3.position.y+.01;n('sternum',0,sy-.025,N.T3.position.z+A.ribCageDepth*.28,.012,MF);for(const s of['L','R']){let g=s==='L'?-1:1;n('g'+s,g*sx,sy,-.01,.02,MF);n('sh'+s,g*sx,sy,0,.028);n('cl'+s,g*A.clavicle*.72,sy+.01,.02,.012,MF);b('sternum','cl'+s,.009);b('cl'+s,'g'+s,.009);b('g'+s,'sh'+s,.007,MF)}
for(const s of['L','R']){let g=s==='L'?-1:1;n('kn'+s,g*hx*.9,knee,kz,.026);n('an'+s,g*hx*.86,ankle,az,.021);n('mid'+s,g*hx*.86,.038,.045,.014,ME);n('toe'+s,g*hx*.86,.025,A.foot*.72,.016,ME);n('heel'+s,g*hx*.86,.025,-A.foot*.2,.014,ME);b('hip'+s,'kn'+s,.019);b('kn'+s,'an'+s,.016);b('an'+s,'mid'+s,.013);b('mid'+s,'toe'+s,.013);b('an'+s,'heel'+s,.01);let ey=sy-A.humerus,wy=ey-A.radius;n('el'+s,g*(sx+.025),ey,.004,.026);n('wr'+s,g*(sx+.035),wy,.01,.020);n('ha'+s,g*(sx+.038),wy-A.hand*.48,.014,.016,ME);n('fi'+s,g*(sx+.04),wy-A.hand,.016,.013,ME);b('sh'+s,'el'+s,.016);b('el'+s,'wr'+s,.013);b('wr'+s,'ha'+s,.012);b('ha'+s,'fi'+s,.009)}sync();
const D=(a,c)=>Math.round(N[a].position.distanceTo(N[c].position)*1000);M.innerHTML=`<h3>Диагностика v0.4</h3><div class="row"><span>Рост</span><span>1750 мм</span></div><div class="row"><span>Femur</span><span>${D('hipL','knL')} мм</span></div><div class="row"><span>Tibia</span><span>${D('knL','anL')} мм</span></div><div class="row"><span>Humerus</span><span>${D('shL','elL')} мм</span></div><div class="row"><span>Radius</span><span>${D('elL','wrL')} мм</span></div><div class="row"><span>L4 z</span><span>${Math.round(N.L4.position.z*1000)} мм</span></div><div class="row"><span>T7 z</span><span>${Math.round(N.T7.position.z*1000)} мм</span></div><div class="row"><span>Hip/Knee/Ankle z</span><span>14 / -24 / -48</span></div>`;
const diag=['S1','L4','L2','T12','T7','T3','C7','C1','skull','hipL','knL','anL'],LE={};for(const k of diag){let d=document.createElement('div');d.className='joint-label';d.textContent=k;LR.appendChild(d);LE[k]=d}document.body.classList.add('labels-hidden');function lab(){for(const k of diag){let p=N[k].position.clone().project(C);LE[k].style.left=(p.x*.5+.5)*innerWidth+'px';LE[k].style.top=(-p.y*.5+.5)*innerHeight+'px'}}function view(v){O.target.set(0,.9,0);if(v==='front')C.position.set(0,1.15,4.7);if(v==='side')C.position.set(4.7,1.15,0);if(v==='back')C.position.set(0,1.15,-4.7);if(v==='threequarter')C.position.set(3.2,1.35,3.2);C.lookAt(O.target);O.update();document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));lab()}document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>view(x.dataset.view));document.querySelector('[data-labels]').onclick=e=>{document.body.classList.toggle('labels-hidden');e.currentTarget.classList.toggle('active');lab()};view('threequarter');addEventListener('resize',()=>{C.aspect=innerWidth/innerHeight;C.updateProjectionMatrix();R.setSize(innerWidth,innerHeight);lab()});R.setAnimationLoop(()=>{O.update();lab();R.render(S,C)});
