import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { scaledAnthropometry } from './anthropometry-v01.js';

/** Skeleton v1.3 — standalone native dynamic anatomical skeleton. */
export const SKELETON_CONTRACT_VERSION=1;
export const SKELETON_VERSION='1.3';

const stature=1.75,A=scaledAnthropometry(stature),H=A.stature;
const app=document.getElementById('app'),metrics=document.getElementById('metrics'),labelsRoot=document.getElementById('labels');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x0b0d12);
const camera=new THREE.PerspectiveCamera(32,innerWidth/innerHeight,.01,100);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2));app.appendChild(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.target.set(0,.9,0);
scene.add(new THREE.HemisphereLight(0xdde8ff,0x1d2330,2.2));const dl=new THREE.DirectionalLight(0xffffff,2);dl.position.set(4,6,5);scene.add(dl);
const grid=new THREE.GridHelper(4,40,0x32405a,0x202735);grid.position.y=.002;scene.add(grid);

const MAT={bone:new THREE.MeshStandardMaterial({color:0xd7dbe7}),joint:new THREE.MeshStandardMaterial({color:0xf0a65b}),frame:new THREE.MeshStandardMaterial({color:0x8a95ae}),vert:new THREE.MeshStandardMaterial({color:0xb8a8ff}),cart:new THREE.MeshStandardMaterial({color:0x8ed3c7}),end:new THREE.MeshStandardMaterial({color:0x7cc7ff})};
const root=new THREE.Group();root.name='rig_root';root.userData.rigVersion=SKELETON_VERSION;scene.add(root);
const joints=new Map(),named=new Map();
function joint(name,parent,local){const g=new THREE.Group();g.name=`joint_${name}`;g.userData.semanticName=name;g.userData.kind='skeleton-joint';g.position.copy(local);parent.add(g);joints.set(name,g);return g}
function node(parent,name,local,r=.018,mat=MAT.joint){const m=new THREE.Mesh(new THREE.SphereGeometry(r,14,10),mat);m.name=name;m.position.copy(local);parent.add(m);named.set(name,m);return m}
function link(parent,name,a,b,r=.011,mat=MAT.bone){const v=b.clone().sub(a),m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,1,10),mat);m.name=name;m.position.copy(a).add(b).multiplyScalar(.5);m.scale.set(1,v.length(),1);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.clone().normalize());parent.add(m);return m}
function worldLocal(parent,p){root.updateMatrixWorld(true);parent.updateMatrixWorld(true);return parent.worldToLocal(p.clone())}
function wn(parent,name,x,y,z,r=.018,mat=MAT.joint){return node(parent,name,worldLocal(parent,new THREE.Vector3(x,y,z)),r,mat)}
function wb(parent,name,A0,B0,r=.011,mat=MAT.bone){return link(parent,name,worldLocal(parent,A0),worldLocal(parent,B0),r,mat)}
function smooth(a,b,t){t=t*t*(3-2*t);return a+(b-a)*t}

const ankleY=A.ankleJointHeight,kneeY=ankleY+A.tibia,hipY=kneeY+A.femur,hx=A.hipCenterHalfWidth,sx=A.shoulderJointHalfWidth;
const s1=hipY+.125,l1=s1+.18,t12=l1+.022,t1=t12+.30,c7=t1+.022,c1=c7+.105;
const c2y=c7+(c1-c7)*.62+.030,c1y=c2y+.032,skY=H-A.headHeight*.50;

// Native torso hierarchy: pelvis -> lumbar -> thoracic -> cervical -> C1 -> head.
const pelvis=joint('pelvis_center',root,new THREE.Vector3(0,hipY+.05,0));
const lumbar=joint('spine_S1',pelvis,new THREE.Vector3(0,s1-(hipY+.05),-.010));
const lumbarTop=joint('spine_L1',lumbar,new THREE.Vector3(0,l1-s1,.005));
const thoracic=joint('spine_T12',lumbarTop,new THREE.Vector3(0,t12-l1,0));
const cervical=joint('spine_T1',thoracic,new THREE.Vector3(0,t1-t12,-.015));
const neckTop=joint('neck_C1',cervical,new THREE.Vector3(0,c1y-t1,.016));
const head=joint('head',neckTop,new THREE.Vector3(0,(skY-.055)-c1y,.024));

// Pelvis anatomy.
const px=A.pelvisWidth*.5,pz=A.pelvisDepth*.5;
for(const side of [-1,1]){const s=side<0?'L':'R',g=side;
 const P={ASIS:new THREE.Vector3(g*px*.90,s1+.047,pz*.64),PSIS:new THREE.Vector3(g*px*.78,s1+.041,-pz*.68),crestA:new THREE.Vector3(g*px*1.06,s1+.088,pz*.12),crestP:new THREE.Vector3(g*px,s1+.086,-pz*.34),acet:new THREE.Vector3(g*hx,hipY+.015,.012),pub:new THREE.Vector3(g*.040,hipY-.022,pz*.52),isch:new THREE.Vector3(g*.082,hipY-.098,-.025),ramus:new THREE.Vector3(g*.060,hipY-.060,pz*.24)};
 for(const [k,p] of Object.entries(P))wn(pelvis,k+s,p.x,p.y,p.z,k==='acet'?.018:k==='isch'?.012:.011,MAT.frame);
 const pairs=[['PSIS','crestP'],['crestP','crestA'],['crestA','ASIS'],['ASIS','acet'],['acet','isch'],['isch','ramus'],['ramus','pub'],['pub','acet']];for(const [a,b] of pairs)wb(pelvis,`${a}${s}_${b}${s}`,P[a],P[b],.008,MAT.frame);
}
wb(pelvis,'pubL_pubR',new THREE.Vector3(-.040,hipY-.022,pz*.52),new THREE.Vector3(.040,hipY-.022,pz*.52),.008,MAT.frame);

// Lumbar spine.
const lumbarPts=[['S1',s1,-.010,.021]];
['L5','L4','L3','L2','L1'].forEach((k,i)=>{const t=(i+1)/5,z=i<2?smooth(-.010,.006,(i+1)/2):smooth(.006,-.005,(i-1)/3);lumbarPts.push([k,s1+(l1-s1)*t,z,.018])});
for(const [k,y,z,r] of lumbarPts)wn(lumbar,k,0,y,z,r,MAT.vert);
for(let i=0;i<lumbarPts.length-1;i++){const a=lumbarPts[i],b=lumbarPts[i+1];wb(lumbar,`${a[0]}_${b[0]}`,new THREE.Vector3(0,a[1],a[2]),new THREE.Vector3(0,b[1],b[2]),.008,MAT.vert)}

// Thoracic spine + rib cage + sternum.
const thorPts=[];Array.from({length:12},(_,i)=>'T'+(12-i)).forEach((k,i)=>{const t=(i+1)/12,z=t<=.5?smooth(-.005,-.050,t/.5):smooth(-.050,-.020,(t-.5)/.5),y=t12+(t1-t12)*t;thorPts.push([k,y,z]);wn(thoracic,k,0,y,z,.015,MAT.vert)});
for(let i=0;i<thorPts.length-1;i++){const a=thorPts[i],b=thorPts[i+1];wb(thoracic,`${a[0]}_${b[0]}`,new THREE.Vector3(0,a[1],a[2]),new THREE.Vector3(0,b[1],b[2]),.008,MAT.vert)}
const tp=Object.fromEntries(thorPts.map(x=>[x[0],new THREE.Vector3(0,x[1],x[2])])),sternY=tp.T3.y-.012;
const man=new THREE.Vector3(0,sternY,tp.T3.z+.095),stern=new THREE.Vector3(0,tp.T7.y-.006,tp.T7.z+.135),xiph=new THREE.Vector3(0,tp.T10.y-.025,tp.T10.z+.118);
wn(thoracic,'manubrium',...man.toArray(),.012,MAT.frame);wn(thoracic,'sternumBody',...stern.toArray(),.011,MAT.frame);wn(thoracic,'xiphoid',...xiph.toArray(),.009,MAT.frame);wb(thoracic,'manubrium_sternumBody',man,stern,.009,MAT.frame);wb(thoracic,'sternumBody_xiphoid',stern,xiph,.007,MAT.frame);
const widths=[.078,.101,.125,.142,.154,.162,.166,.163,.155,.143,.118,.097],fronts=[.058,.070,.086,.100,.112,.121,.127,.125,.118,.108,.090,.074],backs=[.042,.050,.058,.065,.071,.075,.078,.079,.078,.074,.066,.058],drops=[.004,.009,.018,.029,.041,.054,.067,.080,.093,.106,.119,.132],ribVs=['T1','T2','T3','T4','T5','T6','T7','T8','T9','T10','T11','T12'];
for(let i=0;i<12;i++){const p=tp[ribVs[i]];for(const s of['L','R']){const g=s==='L'?-1:1,k=`r${i+1}${s}`,P=new THREE.Vector3(g*widths[i]*.36,p.y-.002,p.z-backs[i]),PL=new THREE.Vector3(g*widths[i]*.78,p.y-drops[i]*.20,p.z-backs[i]*.72),L=new THREE.Vector3(g*widths[i],p.y-drops[i]*.46,p.z+fronts[i]*.18),AL=new THREE.Vector3(g*widths[i]*.86,p.y-drops[i]*.74,p.z+fronts[i]*.66),AA=new THREE.Vector3(g*widths[i]*.64,p.y-drops[i],p.z+fronts[i]);for(const [n,q] of [['P',P],['PL',PL],['L',L],['AL',AL],['A',AA]])wn(thoracic,k+n,...q.toArray(),.006,MAT.frame);for(const [a,b] of [[p,P],[P,PL],[PL,L],[L,AL],[AL,AA]])wb(thoracic,`${k}_rib`,a,b,.0055,MAT.frame);if(i<7)wb(thoracic,`${k}_cart`,AA,i<2?man:stern,.0048,MAT.cart)}}

// Shoulder girdle belongs to the thorax; arms articulate from it.
const sy=tp.T3.y+.01;
for(const s of['L','R']){const g=s==='L'?-1:1,gl=new THREE.Vector3(g*sx,sy,-.010),sh=new THREE.Vector3(g*sx,sy,0),cl=new THREE.Vector3(g*A.clavicle*.72,sy+.010,.020),scMed=new THREE.Vector3(g*.066,tp.T4.y-.004,-.112),scInf=new THREE.Vector3(g*.082,tp.T8.y-.012,-.097),scAc=new THREE.Vector3(g*(sx-.012),sy+.012,-.024),scGlen=new THREE.Vector3(g*(sx-.004),sy-.018,-.015);for(const [n,p,r] of [['g',gl,.018],['sh',sh,.025],['cl',cl,.011],['scMed',scMed,.010],['scInf',scInf,.010],['scAc',scAc,.010],['scGlen',scGlen,.010]])wn(thoracic,n+s,...p.toArray(),r,n==='sh'?MAT.joint:MAT.frame);wb(thoracic,`manubrium_cl${s}`,man,cl,.009);wb(thoracic,`cl_g${s}`,cl,gl,.009);wb(thoracic,`g_sh${s}`,gl,sh,.006,MAT.frame);wb(thoracic,`scMed_scInf${s}`,scMed,scInf,.007,MAT.frame);wb(thoracic,`scInf_scGlen${s}`,scInf,scGlen,.007,MAT.frame);wb(thoracic,`scGlen_scAc${s}`,scGlen,scAc,.007,MAT.frame);wb(thoracic,`scAc_scMed${s}`,scAc,scMed,.007,MAT.frame)}

// Cervical spine.
const cervPts=[];['C7','C6','C5','C4','C3'].forEach((k,i)=>{const t=(i+1)/5,y=c7+(c1-c7)*t*.62,z=smooth(-.020,-.012,t);cervPts.push([k,y,z]);wn(cervical,k,0,y,z,.012,MAT.vert)});cervPts.push(['C2',c2y,-.008],['C1',c1y,-.004]);wn(cervical,'C2',0,c2y,-.008,.016,MAT.vert);wn(cervical,'dens',0,c2y+.024,-.002,.007,MAT.vert);wn(cervical,'C1',0,c1y,-.004,.017,MAT.vert);for(let i=0;i<cervPts.length-1;i++){const a=cervPts[i],b=cervPts[i+1];wb(cervical,`${a[0]}_${b[0]}`,new THREE.Vector3(0,a[1],a[2]),new THREE.Vector3(0,b[1],b[2]),.008,MAT.vert)}wb(cervical,'C2_dens',new THREE.Vector3(0,c2y,-.008),new THREE.Vector3(0,c2y+.024,-.002),.005,MAT.vert);

// Head is terminal on the cervical chain.
const occL=new THREE.Vector3(-.028,c1y+.018,0),occR=new THREE.Vector3(.028,c1y+.018,0),skBase=new THREE.Vector3(0,skY-.055,.020),faceP=new THREE.Vector3(0,skY-.008,.095),jawP=new THREE.Vector3(0,skY-.090,.060),crownP=new THREE.Vector3(0,H,.018);
for(const [n,p,r,m] of [['occL',occL,.010,MAT.frame],['occR',occR,.010,MAT.frame],['skullBase',skBase,.018,MAT.frame],['face',faceP,.018,MAT.frame],['jaw',jawP,.015,MAT.frame],['crown',crownP,.011,MAT.end]])wn(head,n,...p.toArray(),r,m);wb(head,'C1_occL',new THREE.Vector3(0,c1y,-.004),occL,.006,MAT.frame);wb(head,'C1_occR',new THREE.Vector3(0,c1y,-.004),occR,.006,MAT.frame);wb(head,'occL_skullBase',occL,skBase,.006,MAT.frame);wb(head,'occR_skullBase',occR,skBase,.006,MAT.frame);wb(head,'skullBase_face',skBase,faceP,.006,MAT.frame);wb(head,'face_jaw',faceP,jawP,.006,MAT.frame);const skull=new THREE.Mesh(new THREE.SphereGeometry(1,24,18),MAT.vert);skull.name='skull';skull.scale.set(.082,.105,.092);skull.position.copy(worldLocal(head,new THREE.Vector3(0,skY+.012,.018)));head.add(skull);

function buildArm(side){const g=side==='L'?-1:1,shW=new THREE.Vector3(g*sx,sy,0),elW=new THREE.Vector3(g*(sx+.025),sy-A.humerus,.004),wrW=new THREE.Vector3(g*(sx+.035),sy-A.humerus-A.radius,.010),shoulder=joint(`shoulder_${side}`,thoracic,worldLocal(thoracic,shW)),elbow=joint(`elbow_${side}`,shoulder,worldLocal(shoulder,elW)),wrist=joint(`wrist_${side}`,elbow,worldLocal(elbow,wrW));node(shoulder,`shoulder_${side}_dynamic`,new THREE.Vector3(),.025,MAT.joint);node(elbow,`elbow_${side}_dynamic`,new THREE.Vector3(),.023,MAT.joint);node(wrist,`wrist_${side}_dynamic`,new THREE.Vector3(),.017,MAT.joint);link(shoulder,`humerus_${side}`,new THREE.Vector3(),worldLocal(shoulder,elW),.015);const w=worldLocal(elbow,wrW);link(elbow,`radius_${side}`,new THREE.Vector3(),w,.010);const ue=new THREE.Vector3(-g*.011,-.008,-.008),uw=w.clone().add(new THREE.Vector3(-g*.010,-.004,-.006));node(elbow,`ulnaEl_${side}`,ue,.010,MAT.frame);node(elbow,`ulnaWr_${side}`,uw,.008,MAT.frame);link(elbow,`ulna_${side}`,ue,uw,.007,MAT.frame)}
buildArm('L');buildArm('R');

function buildLeg(side){const g=side==='L'?-1:1,hipW=new THREE.Vector3(g*hx,hipY,.014),kneeW=new THREE.Vector3(g*hx*.90,kneeY,-.020),ankW=new THREE.Vector3(g*hx*.86,ankleY,-.048),hip=joint(`hip_${side}`,pelvis,worldLocal(pelvis,hipW)),knee=joint(`knee_${side}`,hip,worldLocal(hip,kneeW)),ankle=joint(`ankle_${side}`,knee,worldLocal(knee,ankW));node(hip,`hip_${side}_head`,new THREE.Vector3(),.026,MAT.joint);const fNeck=new THREE.Vector3(g*(hx+.028),hipY-.032,.008),GT=new THREE.Vector3(g*(hx+.058),hipY-.026,-.006),LT=new THREE.Vector3(g*(hx+.020),hipY-.074,.016),shaft=new THREE.Vector3(g*(hx+.034),hipY-.100,-.006),cm=new THREE.Vector3(g*hx*.90-g*.020,kneeY+.005,-.020),cl=new THREE.Vector3(g*hx*.90+g*.023,kneeY+.003,-.019);for(const [n,p,r] of [['fNeck',fNeck,.014],['GT',GT,.019],['LT',LT,.012],['fShaftTop',shaft,.015],['fCondMed',cm,.020],['fCondLat',cl,.021]])node(hip,n+side,worldLocal(hip,p),r,MAT.frame);for(const [n,a,b,r,m] of [['hip_fNeck',hipW,fNeck,.014,MAT.bone],['fNeck_shaft',fNeck,shaft,.016,MAT.bone],['fNeck_GT',fNeck,GT,.011,MAT.frame],['shaft_LT',shaft,LT,.010,MAT.frame],['femur_med',shaft,cm,.018,MAT.bone],['femur_lat',shaft,cl,.018,MAT.bone]])wb(hip,n+side,a,b,r,m);
 const tm=new THREE.Vector3(g*hx*.90-g*.019,kneeY-.030,-.018),tl=new THREE.Vector3(g*hx*.90+g*.021,kneeY-.031,-.017),tt=new THREE.Vector3(g*hx*.90,kneeY-.057,-.020),fh=new THREE.Vector3(g*hx*.90+g*.036,kneeY-.052,-.022),pat=new THREE.Vector3(g*hx*.90,kneeY-.005,.026),fa=new THREE.Vector3(g*(hx*.86+.032),ankleY+.004,-.050);for(const [n,p,r,m] of [['tPlatMed',tm,.017,MAT.frame],['tPlatLat',tl,.017,MAT.frame],['tShaftTop',tt,.012,MAT.frame],['fibHead',fh,.010,MAT.frame],['fibAn',fa,.009,MAT.frame],['patella',pat,.016,MAT.joint]])node(knee,n+side,worldLocal(knee,p),r,m);for(const [n,a,b,r,m] of [['plateau',tm,tl,.010,MAT.frame],['tibia_med',tm,tt,.013,MAT.bone],['tibia_lat',tl,tt,.013,MAT.bone],['tibia_shaft',tt,ankW,.015,MAT.bone],['fibula',fh,fa,.007,MAT.frame],['patella_link',pat,kneeW,.006,MAT.cart]])wb(knee,n+side,a,b,r,m);
 node(ankle,`ankle_${side}_marker`,new THREE.Vector3(),.019,MAT.joint);const L=A.foot,talus=new THREE.Vector3(ankW.x,ankleY-.018,-.040),calc=new THREE.Vector3(ankW.x,.050,-L*.205),heel=new THREE.Vector3(ankW.x,.025,-L*.255),nav=new THREE.Vector3(ankW.x-g*.010,.060,L*.055),cun=new THREE.Vector3(ankW.x-g*.014,.052,L*.205),cub=new THREE.Vector3(ankW.x+g*.020,.038,L*.175);for(const [n,p,r,m] of [['talus',talus,.015,MAT.joint],['calcaneus',calc,.017,MAT.frame],['heel',heel,.013,MAT.end],['navicular',nav,.010,MAT.frame],['cuneiform',cun,.010,MAT.frame],['cuboid',cub,.010,MAT.frame]])node(ankle,`${n}_${side}`,worldLocal(ankle,p),r,m);for(const [n,a,b,r] of [['talus_calc',talus,calc,.010],['calc_heel',calc,heel,.011],['talus_nav',talus,nav,.008],['calc_cub',calc,cub,.008],['nav_cun',nav,cun,.007],['calc_nav',calc,nav,.006]])wb(ankle,`${n}_${side}`,a,b,r,n==='calc_nav'?MAT.frame:MAT.bone);
 const offs=[-.030,-.015,0,.016,.031].map(v=>v*g),starts=[cun,cun,cun,cub,cub],lens=[.55,.62,.64,.61,.57];for(let i=0;i<5;i++){const base=new THREE.Vector3(ankW.x+offs[i]*.55,i<3?.047:.035,L*.245),mh=new THREE.Vector3(ankW.x+offs[i],i===0?.032:.025,L*lens[i]),t1p=new THREE.Vector3(ankW.x+offs[i]*1.05,.020,L*(lens[i]+.105)),tip=new THREE.Vector3(ankW.x+offs[i]*1.08,.016,L*(lens[i]+(i===0?.205:.175)));for(const [n,p,r,m] of [['base',base,.007,MAT.frame],['head',mh,i===0?.009:.007,MAT.frame],['toe1',t1p,.006,MAT.frame],['tip',tip,.006,MAT.end]])node(ankle,`${n}_${side}_${i}`,worldLocal(ankle,p),r,m);wb(ankle,`mt1_${side}_${i}`,starts[i],base,.006,MAT.frame);wb(ankle,`mt2_${side}_${i}`,base,mh,i===0?.008:.006);wb(ankle,`toe1_${side}_${i}`,mh,t1p,i===0?.007:.0055);wb(ankle,`toe2_${side}_${i}`,t1p,tip,i===0?.0065:.0048)}}
buildLeg('L');buildLeg('R');

function buildHand(side){const g=side==='L'?-1:1,wrist=joints.get(`wrist_${side}`),grp=new THREE.Group();grp.name=`hand_${side}`;wrist.add(grp);const prox=[],dist=[],lat=[.018,.006,-.007,-.019];for(let i=0;i<4;i++)prox.push(node(grp,`carpal_p_${side}_${i}`,new THREE.Vector3(g*lat[i],-.018,i===0?.006:i===3?-.005:0),.0055,MAT.frame));for(let i=0;i<4;i++)dist.push(node(grp,`carpal_d_${side}_${i}`,new THREE.Vector3(g*lat[i]*1.08,-.040,Math.abs(i-1.5)*.004),.0055,MAT.frame));for(let i=0;i<3;i++){link(grp,`cp_${side}_${i}`,prox[i].position,prox[i+1].position,.0028,MAT.frame);link(grp,`cd_${side}_${i}`,dist[i].position,dist[i+1].position,.0028,MAT.frame)}const mcX=[.030,.018,.004,-.011,-.026],mcLen=[.064,.086,.091,.085,.076],heads=[];for(let i=0;i<5;i++){const base=dist[Math.min(i,3)],h=node(grp,`metacarpal_head_${side}_${i}`,new THREE.Vector3(g*mcX[i],-.040-mcLen[i],i===0?.020:Math.abs(i-2)*.003),i===0?.0065:.0058,MAT.frame);link(grp,`metacarpal_${side}_${i}`,base.position,h.position,i===0?.0048:.0042);heads.push(h)}const segs=[[.043,.026,.021],[.048,.030,.023],[.044,.028,.022],[.036,.023,.019]];for(let f=1;f<5;f++){let q=heads[f];for(let j=0;j<3;j++){const t=node(grp,`finger_${side}_${f}_${j}`,new THREE.Vector3(q.position.x+(2.2-f)*.003*g,q.position.y-segs[f-1][j],q.position.z+(j===2?.002:0)),j===2?.0045:.005,j===2?MAT.end:MAT.frame);link(grp,`phalanx_${side}_${f}_${j}`,q.position,t.position,j===0?.0038:.0033);q=t}}let q=heads[0],th1=node(grp,`thumb_ip_${side}`,new THREE.Vector3(q.position.x+g*.022,q.position.y-.031,q.position.z+.012),.0055);link(grp,`thumb_prox_${side}`,q.position,th1.position,.0042);const th2=node(grp,`thumb_tip_${side}`,new THREE.Vector3(th1.position.x+g*.014,th1.position.y-.026,th1.position.z+.006),.005,MAT.end);link(grp,`thumb_dist_${side}`,th1.position,th2.position,.0038)}
buildHand('L');buildHand('R');

function getJoint(name){return joints.get(name)||null}
const SEGMENTS={thigh_L:['hip_L','knee_L'],shin_L:['knee_L','ankle_L'],thigh_R:['hip_R','knee_R'],shin_R:['knee_R','ankle_R'],upperarm_L:['shoulder_L','elbow_L'],forearm_L:['elbow_L','wrist_L'],upperarm_R:['shoulder_R','elbow_R'],forearm_R:['elbow_R','wrist_R'],lumbar:['spine_S1','spine_T12'],thoracic:['spine_T12','spine_T1'],cervical:['spine_T1','neck_C1']};
function getSegment(name){const d=SEGMENTS[name];if(!d)return null;const a=getJoint(d[0]),b=getJoint(d[1]);if(!a||!b)return null;const start=a.getWorldPosition(new THREE.Vector3()),end=b.getWorldPosition(new THREE.Vector3());return{name,a:d[0],b:d[1],start,end,length:start.distanceTo(end)}}
function resetPose(){for(const j of joints.values())j.quaternion.identity();root.updateMatrixWorld(true)}
function getRestMetrics(){const segments={};for(const n of Object.keys(SEGMENTS))segments[n]=getSegment(n)?.length??null;return{stature,segments}}
function rebuildRestPose({stature:newStature=stature}={}){if(Math.abs(newStature-stature)>.000001)throw new Error('Skeleton v1.3: stature rebuild after dynamic torso validation');resetPose();return getRestMetrics()}
const api=Object.freeze({contractVersion:SKELETON_CONTRACT_VERSION,skeletonVersion:SKELETON_VERSION,jointNames:Object.freeze([...joints.keys()]),segmentNames:Object.freeze(Object.keys(SEGMENTS)),jointRoot:root,getJoint,getSegment,getRestMetrics,rebuildRestPose,resetPose});root.userData.skeletonAPI=api;scene.userData.skeletonContractVersion=1;scene.userData.skeletonVersion=SKELETON_VERSION;

const gravity=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,H+.05,0)]),new THREE.LineBasicMaterial({color:0xff7f7f}));scene.add(gravity);
metrics.innerHTML=`<h3>Диагностика v1.3</h3><div class="row"><span>Рост</span><span>1750 мм</span></div><div class="row"><span>Architecture</span><span>standalone dynamic</span></div><div class="row"><span>Contract</span><span>v1</span></div><div class="row"><span>Limbs</span><span>native L/R</span></div><div class="row"><span>Torso</span><span>pelvis → lumbar → thoracic → cervical → head</span></div>`;
const title=document.querySelector('.info .title');if(title)title.textContent='Skeleton v1.3';const sub=document.querySelector('.info .sub');if(sub)sub.innerHTML='standalone dynamic body · contract v1<br>рост 1750 мм · без адаптеров';
const labelNames=['S1','L4','T7','C2','C1','skullBase'],LE={};for(const k of labelNames){const o=named.get(k);if(!o)continue;const d=document.createElement('div');d.className='joint-label';d.textContent=k;labelsRoot.appendChild(d);LE[k]=[d,o]}document.body.classList.add('labels-hidden');function lab(){for(const[d,o]of Object.values(LE)){const p=o.getWorldPosition(new THREE.Vector3()).project(camera);d.style.left=(p.x*.5+.5)*innerWidth+'px';d.style.top=(-p.y*.5+.5)*innerHeight+'px'}}function view(v){controls.target.set(0,.9,0);if(v==='front')camera.position.set(0,1.15,4.7);if(v==='side')camera.position.set(4.7,1.15,0);if(v==='back')camera.position.set(0,1.15,-4.7);if(v==='threequarter')camera.position.set(3.2,1.35,3.2);camera.lookAt(controls.target);controls.update();document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));lab()}document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>view(x.dataset.view));const labelsBtn=document.querySelector('[data-labels]');if(labelsBtn)labelsBtn.onclick=e=>{document.body.classList.toggle('labels-hidden');e.currentTarget.classList.toggle('active');lab()};view('threequarter');addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);lab()});renderer.setAnimationLoop(()=>{controls.update();lab();renderer.render(scene,camera)});
export {api as skeletonAPI};